
LW=0.01;FS=9;FW='demi';



figure
  % All together
  
plot(fiftyfiftyt, fiftyfiftySCV,'b-o', fiftyfiftyt, fiftyfiftySCG,'r-o', ...
    monoCVt, monoSCV,'b--+', monoCGt, monoSCG, 'r--+', ...
    ninetycvtencgt, ninetycvtencgSCV,'b-*', ninetycvtencgt, ninetycvtencgSCG,'r-*', ...
    ninetycgtencvt, ninetycgtencvSCV,'b-.', ninetycgtencvt, ninetycgtencvSCG,'r-.',  ...
    ninetycvtencgwatert, ninetycvtencgwaterSCV, 'b-x', ninetycvtencgwatert, ninetycvtencgwaterSCG, 'r-x', ...
    sixtycvfortycgt, sixtycvfortycgSCV,'b--^', sixtycvfortycgt, sixtycvfortycgSCG, 'r--^', ...
    sixtycgfortycvt, sixtycgfortycvSCV,'b-->', sixtycgfortycvt, sixtycgfortycvSCG,'r-->')
title('SUSCEPTIBLES','FontSize',FS,'FontWeight',FW)
legend({'50%CV', '50%CG', ...
    'MonoCV', 'MonoCG', ...
    '90%CV', '10%CG', ...
    '90%CG', '10%CV', ...
   '90%CV.Water', '10%CG.Water', ...
   '60%CV', '40%CG', ...
   '60%CG','40%CV'})
xlabel('Time (days)','FontSize',FS,'FontWeight',FW)
ylabel('Individuals m^{-2}','FontSize',FS,'FontWeight',FW)   
set(gca,'LineWidth',LW,'FontSize',FS,'FontWeight',FW)  
  

figure

plot( fiftyfiftyt, fiftyfiftyICV,'b-o', fiftyfiftyt, fiftyfiftyICG,'r-o', ... 
monoCVt, monoICV,'b--+', monoCGt, monoICG, 'r--+',...
ninetycvtencgt, ninetycvtencgICV,'b-*', ninetycvtencgt, ninetycvtencgICG,'r-*', ...
ninetycgtencvt, ninetycgtencvICV,'b-.', ninetycgtencvt, ninetycgtencvICG,'r-.', ...
ninetycvtencgwatert, ninetycvtencgwaterICV, 'b-x', ninetycvtencgwatert, ninetycvtencgwaterICG, 'r-x', ...
sixtycgfortycvt, sixtycgfortycvICV,'b-->', sixtycgfortycvt, sixtycgfortycvICG,'r-->', ...
sixtycvfortycgt, sixtycvfortycgICV,'b--^', sixtycvfortycgt, sixtycvfortycgICG,'r--^', 'LineWidth',LW) 
title('Infected','FontSize', FS, 'FontWeight',FW)
legend({'50%CV', '50%CG', ...
    'MonoCV', 'MonoCG', ...
    '90%CV', '10%CG', ...
    '90%CG', '10%CV', ...
   '90%CV.Water', '10%CG.Water', ...
   '60%CG', '40%CV', ...
   '60%CV','40%CG'})
xlabel('Time (days)','FontSize',FS,'FontWeight',FW)
ylabel('Individuals m^{-2}','FontSize',FS,'FontWeight',FW)
set(gca,'LineWidth',LW,'FontSize',FS,'FontWeight',FW) 


figure

plot(fiftyfiftyt, fiftycummortCV,'bo', fiftyfiftyt, fiftycummortCG,'ro', ...
    monoCVt, monocummortCV,'b-+', monoCGt, monocummortCG, 'r-+', ...
    ninetycvtencgt, ninetycvcummortCV,'b*', ninetycvtencgt, ninetycvcummortCG,'r*', ...
    ninetycgtencvt, ninetycgcummortCV,'bo-', ninetycgtencvt, ninetycgcummortCG,'ro-', ...
    ninetycvtencgwatert, ninetycvcummortCVwater, 'bx', ninetycvtencgwatert, ninetycvcummortCGwater, 'rx', ...
    sixtycgfortycvt, fortycvcummortCV,'b>', sixtycgfortycvt, fortycvcummortCG,'r>', ...
    sixtycvfortycgt, sixtycvcummortCV,'b^', sixtycvfortycgt, sixtycvcummortCG,'r^', ... %we have validation data from hereon 
   deadtime, deadCgigauvar, 'k-o', ...
   deadtime, deadCvirguvar, 'k-+',...
   deadtime, deadCvirgAus, 'k-*' ,...
   deadtime, deadCgigaAus, 'k-.', ...
   deadday, deadS1, 'k-x', ...
   deadday, deadS2, 'k->', ...
   deadday, deadS3, 'k-<', ...
   deadday, deadR41, 'k-^', ...
   deadday, deadR42, 'k-^', ...
   deadday, deadR43, 'k-^', 'LineWidth',LW)
xlim([0,15])

title('Cumulative Mortality(%)','FontSize',FS,'FontWeight',FW)
legend({'50%CV', '50%CG', 'MonoCV', 'MonoCG', ...
    '90%CV', '10%CG', ...
    '10%CV','90%CG' ,...
   '90%CV.Water', '10%CG.Water', ...
   '60%CG', '40%CV', ...
   '60%CV','40%CG' ...
   'CG_m_o_n_oFRAvar', ...
    'CV_m_o_n_oFRAvar', ...
   'CV_m_o_n_oAUSvar', ...
    'CG_m_o_n_oAUSuvar', ...
    'CGs1', ...
    'CGs2', ...
    'CGs3', ...
    'CGr41', ...
    'CGr42', ...
    'CGr43'})
xlabel('Time (days)','FontSize',FS,'FontWeight',FW)
ylabel('Mortality(%)','FontSize',FS,'FontWeight',FW)
set(gca,'LineWidth',LW,'FontSize',FS,'FontWeight',FW) 


figure
plot(fiftyfiftyt,fiftyfiftyP,'g-o', ...
    monoCVt, monoCVP, 'g-+', ...
    monoCGt, monoCGP, 'g-+', ...
    ninetycgtencvt,ninetycgtencvP,'g-.', ...
    ninetycvtencgt, ninetycvtencgP,'g-*', ...
    ninetycvtencgwatert, ninetycvtencgwaterP,'g-x', ...
    sixtycgfortycvt, sixtycgfortycvP,'g>-', ...
    sixtycvfortycgt, sixtycvfortycgP,'g^-','LineWidth',LW)
xlim([0,15])
title('Infectious Particles','FontSize',FS,'FontWeight',FW)
legend({'50% both spps', ...
    'MonoCV', ...
    'MonoCG', ...
    '90%CG + 10CV', ...
    '90%CV + 10CG', ...
    '90%CV.Water',...
   '60%CG + 40%CV', ...
   '60%CV + 40%CG'})
xlabel('Time (days)','FontSize',FS,'FontWeight',FW)
ylabel('Pathogens m^{-3}','FontSize',FS,'FontWeight',FW)
set(gca,'LineWidth',LW,'FontSize',FS,'FontWeight',FW)








